In [8]:
import pandas as pd
df = pd.read_csv('cars.zip')
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [10]:
import pandas as pd
import zipfile

zf = zipfile.ZipFile('cars.zip') 
df = pd.read_csv(zf.open('cars.csv'))
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [1]:
from zipfile import ZipFile 

# specifying the zip file name 
file_name = "cars.zip"

# opening the zip file in READ mode 
with ZipFile(file_name, 'r') as zip: 
    # printing all the contents of the zip file 
    zip.printdir() 

    # extracting all the files 
    print('Extracting all the files now...') 
    zip.extractall() 
    print('Done!')

File Name                                             Modified             Size
cars.csv                                       2020-07-13 09:28:14         1783
Extracting all the files now...
Done!

In [61]:
import zipfile

def main():
    with zipfile.ZipFile('cars.zip') as file:
        # ZipFile.infolist() returns a list containing all the members of an archive file
        print(file.infolist())
        print("----------------------")
        # ZipFile.namelist() returns a list containing all the members with names of an archive file
        print(file.namelist())
        print("----------------------")
        # ZipFile.open(path = filepath, mode = mode_type, pwd = password) opens the members of an archive file
        # 'pwd' is optional -> if it has password mention otherwise leave it
        text_file = file.open(name = file.namelist()[-1], mode = 'r')
        # 'read()' method of the file prints all the content of the file. You see this method in file handling.
        print(text_file.read()) 
       
              
        file.close()

if __name__ == '__main__': main()

[<ZipInfo filename='cars.csv' compress_type=deflate external_attr=0x20 file_size=1783 compress_size=848>]
----------------------
['cars.csv']
----------------------
b'"","mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"\n"Mazda RX4",21,6,160,110,3.9,2.62,16.46,0,1,4,4\n"Mazda RX4 Wag",21,6,160,110,3.9,2.875,17.02,0,1,4,4\n"Datsun 710",22.8,4,108,93,3.85,2.32,18.61,1,1,4,1\n"Hornet 4 Drive",21.4,6,258,110,3.08,3.215,19.44,1,0,3,1\n"Hornet Sportabout",18.7,8,360,175,3.15,3.44,17.02,0,0,3,2\n"Valiant",18.1,6,225,105,2.76,3.46,20.22,1,0,3,1\n"Duster 360",14.3,8,360,245,3.21,3.57,15.84,0,0,3,4\n"Merc 240D",24.4,4,146.7,62,3.69,3.19,20,1,0,4,2\n"Merc 230",22.8,4,140.8,95,3.92,3.15,22.9,1,0,4,2\n"Merc 280",19.2,6,167.6,123,3.92,3.44,18.3,1,0,4,4\n"Merc 280C",17.8,6,167.6,123,3.92,3.44,18.9,1,0,4,4\n"Merc 450SE",16.4,8,275.8,180,3.07,4.07,17.4,0,0,3,3\n"Merc 450SL",17.3,8,275.8,180,3.07,3.73,17.6,0,0,3,3\n"Merc 450SLC",15.2,8,275.8,180,3.07,3.78,18,0,0,3,3\n"Cadillac Fleetwood",10.4,8,472,205,2.93,5.25,17.98,0,0,3,4\n"Lincoln Continental",10.4,8,460,215,3,5.424,17.82,0,0,3,4\n"Chrysler Imperial",14.7,8,440,230,3.23,5.345,17.42,0,0,3,4\n"Fiat 128",32.4,4,78.7,66,4.08,2.2,19.47,1,1,4,1\n"Honda Civic",30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2\n"Toyota Corolla",33.9,4,71.1,65,4.22,1.835,19.9,1,1,4,1\n"Toyota Corona",21.5,4,120.1,97,3.7,2.465,20.01,1,0,3,1\n"Dodge Challenger",15.5,8,318,150,2.76,3.52,16.87,0,0,3,2\n"AMC Javelin",15.2,8,304,150,3.15,3.435,17.3,0,0,3,2\n"Camaro Z28",13.3,8,350,245,3.73,3.84,15.41,0,0,3,4\n"Pontiac Firebird",19.2,8,400,175,3.08,3.845,17.05,0,0,3,2\n"Fiat X1-9",27.3,4,79,66,4.08,1.935,18.9,1,1,4,1\n"Porsche 914-2",26,4,120.3,91,4.43,2.14,16.7,0,1,5,2\n"Lotus Europa",30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2\n"Ford Pantera L",15.8,8,351,264,4.22,3.17,14.5,0,1,5,4\n"Ferrari Dino",19.7,6,145,175,3.62,2.77,15.5,0,1,5,6\n"Maserati Bora",15,8,301,335,3.54,3.57,14.6,0,1,5,8\n"Volvo 142E",21.4,4,121,109,4.11,2.78,18.6,1,1,4,2\n'

In [47]:
## zipfile.ZipInfo
import zipfile

def main():
    with zipfile.ZipFile('cars.zip') as file:

        # 'infolist()' is the object of 'ZipFile' class
        # 'infolist()' returns a list containing all the folders and files of the zip -> 'ZipInfo' objects
        # assigning last element of the list to a variable to test all the methods of 'ZipInfo'
        archive = file.infolist()
        read_me_file = archive[-1]

        # 'ZipInfo' methods

        # ZipInfo_object.filename returns the name of the file
        print("Name of the file:- {}".format(read_me_file.filename))

        # ZipInfo_object.file_size returns the size of the file
        print("Size of the file:- {}".format(read_me_file.file_size))

        # ZipInfo_object.is_dir() returns True if it's directory otherwise False
        print("Is directory:- {}".format(read_me_file.is_dir()))

        # ZipInfo_object.date_time() returns the created date & time of file
        print("File created data & time:- {}".format(read_me_file.date_time))

if __name__ == '__main__': main()

Name of the file:- cars.csv
Size of the file:- 1783
Is directory:- False
File created data & time:- (2020, 7, 13, 9, 28, 14)

In [50]:
## extracting zip with password
import zipfile

def main():
    file_name = 'cars.zip'
    pswd = 'datacamp'

    with zipfile.ZipFile(file_name) as file:
        # password you pass must be in the bytes you converted 'str' into 'bytes'
        file.extractall(pwd = bytes(pswd, 'utf-8'))

if __name__ == '__main__': main()

In [71]:
import zipfile
with zipfile.ZipFile('Images.zip') as file:
    lst = file.namelist()
    count=0
    for ele in lst:
        count+=1
        print(ele)
#     print("Total number of files in "+ file.filename +" is "+ str(count))
    print("Total number of files in "+ file.filename +" is  {}".format(count))

Working with Images/
Working with Images/.ipynb_checkpoints/
Working with Images/.ipynb_checkpoints/Working with pillo-checkpoint.ipynb
Working with Images/blue_color.jpg
Working with Images/example.jpg
Working with Images/mask.png
Working with Images/pencils.jpg
Working with Images/purple.png
Working with Images/red_color.jpg
Working with Images/word_matrix.png
Working with Images/Working with pillo.ipynb
Total number of files in Images.zip is  11

In [73]:
import pandas as pd
import zipfile

zf = zipfile.ZipFile('cars.zip') 
df = pd.read_csv(zf.open('cars.csv'))
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [75]:
import sys
from zipfile import ZipFile
from PIL import Image # $ pip install pillow

filename = "new.zip"
with ZipFile(filename) as archive:
    for entry in archive.infolist():
        with archive.open(entry) as file:
            img = Image.open(file)
            print(img.size, img.mode, len(img.getdata()))

(3456, 4608) RGB 15925248